### ISSUE TITLE
iOS compatibility

### ISSUE THREAD

**Issue by BraveFriends** [wader/aes-arraybuffer#1]
Really appreciate your efforts on this library.
It has been worked very well and save lots of my time until I ran this on iPhone.

I don't think it's an issue from this library(maybe from iOS's problem), but wondering if there might be any work-around.

Issue: tests.html simply fail on iPhone, especially at test_aes_cbc_padding_symmetric()

**Comment by wader** [comment]
Thanks! I think i've seen it and the weird thing is that if you run with the remote Safari inspector everything works fine. I suspect they use different JavaScript engines or options when in running in debug somehow, so your guess is probably right that this is a JIT bug of something similar. Probably some JIT optimization that only triggers after running the same code enough times.

I did a fast try at minimizing down the code that cause the bug here http://jsfiddle.net/Taq3m/ (run on iOS or Safari in OSX which seems to have the same bug) and if you get an alert you have triggered the bug. Search for variable "loops", 47 triggers the bug for me, 46 works fine. It is a bit hard to minimize without breaking stuff :( Tips is to verify run with inspector open.

If we can't fix it or work-around the bug maybe it is possible to use a typed arrayed polyfill for known broken browsers? like https://github.com/inexorabletash/polyfill/blob/master/typedarray.js ...but it will not be fast.

What kind of project are you working on? a bit curious :)

**Comment by wader** [comment]
Managed to remove some more code http://jsfiddle.net/Dz4Tw/

**Comment by wader** [comment]
A bit closer http://jsfiddle.net/B6zja/

Somehow

```
s0 = (state_u32[0] ^ w[nr]) >>> 0;
```

Is compiled the wrong way the 47th loop, s0 should be:

```
0b10110101 01111101 00110001 11101001
```

But ends up being

```
0b00111101 00100000 00000000 00000000
```

**Comment by wader** [comment]
Seems to work fine with [WebKit-SVN-r155573.dmg](http://builds.nightly.webkit.org/files/trunk/mac/WebKit-SVN-r155573.dmg) but not sure if the bug has been fixed or if Safari uses another JavaScript engine.

**Comment by wader** [comment]
@BraveFriends  did you get anywhere with this?

**Comment by wader** [comment]
@BraveFriends close?
